### ISSUE TITLE
Error when preview in browser mode

### ISSUE THREAD

**Issue by havewisdom** [ijgnd/anki__pdf_viewer_with_pdfjs#2]
Hello, thank you for creating a great extension app.
There is no problem in study mode, but if I click the link through "preview in browser mode", an error will appear.

<img width="612" alt="스크린샷 2020-03-16 오후 4 31 59" src="https://user-images.githubusercontent.com/62235227/76733623-83b20180-67a4-11ea-893d-5b9a74f15e5d.png">

**Comment by ijgnd** [comment]
Sorry I somehow missed this report.

If you still use this add-on: Can you still reproduce this in Anki 2.1.26? If so you would help me a lot by providing some info because I can't reproduce the problem and I don't know where to look: 

- your add-on config. the filename, a screenshot of the note in the editor, the source code of the field (ctrl+shift+x when your cursor is in the field with the filename).
- From the main window click on Help->About. In the window that opens click the "Copy Debug Info" Button and share the copied text.

**Comment by havewisdom** [comment]
Anki 2.1.15 (442df9d6) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=1

Add-ons:

TagSelectorV2 (비활성화됨)
Basic Printing Support
Speed Focus Mode auto-alert auto-reveal auto-fail (비활성화됨)
Resize images in editor
Links between notes cards to open browser and previewer
  Advanced Review Bottom Bar  
Postpone cards review (비활성화됨)
Create subs2srs cards with mpv video player
ImageResizer
Add Table (비활성화됨)
Field History
Image Occlusion Enhanced for Anki 21 alpha
Search and Replace Tags
link cardsnotes and preview them in extra window
Simple PDF Page Link Handler (비활성화됨)
Symbols
Night Mode
Touch Wood Show New Cards Left Hint (비활성화됨)
Media Import (비활성화됨)
More Decks Stats and Time Left (비활성화됨)
Multiple Choice for Anki
Show fields source html in editor
Image Style Editor (비활성화됨)
Touch Screen - draw and write on your cards (비활성화됨)
MIA Retirement
Add note id (비활성화됨)
Hoarders Delight RecycleTrash Bin (비활성화됨)
Searching PDF Reading  Note-Taking in Add Dialog (비활성화됨)
Fast Word Query Multi-threaded queries for words from local or web dictionaries (비활성화됨)
Interactive Cards for language learning (비활성화됨)
Browser MaximizeHide TableEditor
Large and Colorful Buttons
Zoom 21
Sort by Card Type Note Type or Deck Name
Advanced Copy Fields
High Yield Tags (비활성화됨)
Fill the blanks - Multiple typecloze support
External Note Editor for the Browser
Symbols As You Type
AnkiConnect (비활성화됨)
LPCG LyricsPoetry Cloze Generator
Progress Bar (비활성화됨)
Automatic Basic to Cloze (비활성화됨)
More Overview Stats
Duplicate Selected Notes
Highlight Search Results in the Browser
Customize Keyboard Shortcuts
Quick Colour Changing
Button Colours Good Again (비활성화됨)
Progress Graphs and Stats for Learned and Matured Cards (비활성화됨)
Batch Editing
Mini Format Pack
Reset Card Scheduling
Add Hyperlink
pdf viewer
ReMemorize Rescheduler with sibling and logging v140
editor - remove more formatting for selection headings hyperlinks 
Multi-column note editor
Opening the same window multiple time
Edit Field During Review Cloze
Frozen-field compatible with other add-on
Keep model of add cards
AwesomeTTS for Anki 21 updated (비활성화됨)
Fastbar- with nightmode support (비활성화됨)
Replay buttons on card
Frozen Fields (비활성화됨)
Batch Download Pictures From Google Images (비활성화됨)
Blitzkrieg II - Advanced Browser Sidebar BETA8
Hierarchical Tags 2 (비활성화됨)
True Retention (비활성화됨)
Set Font Size
Syllabus - Anki Statistics and Export by Tag and Deck (비활성화됨)
ReviewHeatmap
Additional Card Fields Fork for 21
Browser TableEditor side-by-side horizontal split
Web Browser - Search terms Import texts and images automatically (비활성화됨)
Advanced Browser
Enhance main window (비활성화됨)
Ze Add note id
Editor Autocomplete (비활성화됨)
Modified reviewer context menu search with browser search
Incremental Reading v4103 (비활성화됨)
Watch Foreign Language Movies with Anki

**Comment by havewisdom** [comment]
demo video in anki 2.1.15 of error in preview mode
![pdfviewer](https://user-images.githubusercontent.com/62235227/82768137-125b9280-9e68-11ea-9ff3-3dead5357408.gif)

**Comment by havewisdom** [comment]
Good morning. Thank you for answering this old report.
As I used Anki deeply, I realized that most of the additional functions that I use were created by some developers. Thank you very much.

I needed this app at a time when it was necessary to build links between materials, and I used it really well for a while.
But in fact, I don't use it now. I am using this function by copying the x-callback link from other pdf related software into an hyperlink from anki.

It is a great pleasure to use the ones you have developed and thank you once again for greatly saving your work.
If you need more user related information, please feel free to tell us. I hope it can be a little helpful.
Thank you.

**Comment by ijgnd** [comment]
thanks for sharing all this info. Unfortunately your gif was so small I couldn't see any details. I just updated the ankiweb listing with a version that works with the Preview window
