### ISSUE TITLE
A little bit of thanks

### ISSUE THREAD

**Issue by aboali1hassona** [ijgnd/anki__pdf_viewer_with_pdfjs#5]
Hi, @ijgnd 
I prepared this little contribution for the growing popularity of this great ADDon.
because this helpful ADDon makes my study easier and saves time for Adding Cards and Notes.
https://youtu.be/wQmAtxS59mU

**Comment by ijgnd** [comment]
Sorry for answering so late. I don't know how, but i managed to miss your post. Your video is pretty cool and much better than my screencasts. Thanks for creating this video! I added it to the top of the ankiweb description.

I just uploaded a new version that has some improvements like the option to put references into other fields (the syntax is ___filename____pagenum), a dialog that allows you to quickly select the relevant pdf from the pdf-folder in the editor and a new pdf viewer for 2.1.50/qt6 that should be faster.

If you still use this add-on maybe that's interesting. I could have introduced bugs. If you find one please let me know.

**Comment by ijgnd** [comment]
btw: I made a new version that should better handle non-western characters in filenames.

Before I upload it to ankiweb it needs some testing.

If you are interested: https://github.com/ijgnd/anki__pdf_viewer_with_pdfjs/releases/download/2022-07-15/anki__pdf_viewer_with_pdfjs__2022-07-15.ankiaddon
