### ISSUE TITLE
Field modifier randomly 

### ISSUE THREAD

**Issue by Deus333** [ijgnd/anki__pdf_viewer_with_pdfjs#7]
Hi, brother could you pls help me with the Field modifier randomly add on? I don't know how exactly to work with...
I'll appreciate it

**Comment by ijgnd** [comment]
I've forgotten that I ever uploaded this add-on. I haven't looked at it in years. So I can't help. I would search the anki subreddit or the official forum with terms liks "image random field" and if there isn't something ask a question.

**Comment by Deus333** [comment]
Oh my God I did it thanks aaaaaalooot
